Update for 08-18
Since all the Perfect repos have been updated for the 08-18 snapshot, compiling with the 08-04 version will no longer work due to compilation errors.

Fixes `error: @escaping attribute only applies to function types`